// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketWave.Repository.Entity;

[Table("Concert")]
[Index("PerformanceDate", Name = "IX_Concert_PerformanceDate")]
[Index("Status", Name = "IX_Concert_Status")]
public partial class Concert
{
    [Key]
    public Guid ConcertId { get; set; }

    [Required]
    [StringLength(200)]
    public string ConcertName { get; set; }

    [Required]
    [StringLength(100)]
    public string ArtistName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PerformanceDate { get; set; }

    [Required]
    [StringLength(100)]
    public string VenueName { get; set; }

    [StringLength(200)]
    public string VenueAddress { get; set; }

    [StringLength(1000)]
    public string Description { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string PosterImageUrl { get; set; }

    public int Status { get; set; }

    public int TotalSeats { get; set; }

    public int AvailableSeats { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SaleStartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SaleEndDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateDate { get; set; }

    [InverseProperty("Concert")]
    public virtual ICollection<Seat> Seats { get; set; } = new List<Seat>();
}