// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketWave.Repository.Entity;

[Table("Member")]
[Index("Email", Name = "IX_Members_Email", IsUnique = true)]
[Index("NationalID", Name = "IX_Members_NationalID", IsUnique = true)]
public partial class Member
{
    [Key]
    public Guid MemberId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string NationalID { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string BirthDate { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(100)]
    public string Address { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateDate { get; set; }
    //public object Orders { get; set; }
}