// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TicketWave.Repository.Entity;

public partial class MemberDbContext : DbContext
{
    public MemberDbContext(DbContextOptions<MemberDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Member> Members { get; set; }
    public virtual DbSet<Order> Orders { get; set; }
    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Concert> Concerts { get; set; }
    public virtual DbSet<Seat> Seats { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK_Members");

            entity.Property(e => e.MemberId).ValueGeneratedNever();
            //entity.Property(e => e.Password).HasDefaultValue("", "DF__Members__Passwor__5AEE82B9");
            entity.Property(e => e.Password).HasDefaultValue("");
        });

        // Order 設定
        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK_Orders");
            entity.Property(e => e.OrderId).ValueGeneratedNever();

            // 設定與 Member 的關聯
            entity.HasOne(d => d.Member)
                .WithMany()
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_Order_Member");
        });

        // OrderDetail 設定
        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK_OrderDetails");
            entity.Property(e => e.OrderDetailId).ValueGeneratedNever();

            // 設定與 Order 的關聯（刪除訂單時一併刪除明細）
            entity.HasOne(d => d.Order)
                .WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_OrderDetail_Order");
        });


        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}