// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketWave.Repository.Entity;

[Table("Order")]
[Index("ConcertId", Name = "IX_Order_ConcertId")]
[Index("MemberId", Name = "IX_Order_MemberId")]
[Index("OrderNumber", Name = "IX_Order_OrderNumber", IsUnique = true)]
public partial class Order
{
    [Key]
    public Guid OrderId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string OrderNumber { get; set; }

    public Guid MemberId { get; set; }

    public Guid ConcertId { get; set; }

    [StringLength(200)]
    public string ConcertName { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal TotalAmount { get; set; }

    public int TicketCount { get; set; }

    public int OrderStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateDate { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("Orders")]
    public virtual Member Member { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}