// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketWave.Repository.Entity;

[Table("OrderDetail")]
public partial class OrderDetail
{
    [Key]
    public Guid OrderDetailId { get; set; }

    public Guid OrderId { get; set; }

    [Required]
    [StringLength(20)]
    public string SeatZone { get; set; }

    [Required]
    [StringLength(10)]
    public string SeatRow { get; set; }

    [Required]
    [StringLength(10)]
    public string SeatNumber { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    public int TicketStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderDetails")]
    public virtual Order Order { get; set; }
}