// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketWave.Repository.Entity;

[Table("Seat")]
[Index("ConcertId", Name = "IX_Seat_ConcertId")]
[Index("SeatStatus", Name = "IX_Seat_Status")]
[Index("ConcertId", "SeatZone", "SeatRow", "SeatNumber", Name = "IX_Seat_Unique", IsUnique = true)]
public partial class Seat
{
    [Key]
    public Guid SeatId { get; set; }

    public Guid ConcertId { get; set; }

    [Required]
    [StringLength(20)]
    public string SeatZone { get; set; }

    [Required]
    [StringLength(10)]
    public string SeatRow { get; set; }

    [Required]
    [StringLength(10)]
    public string SeatNumber { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    public int SeatStatus { get; set; }

    public Guid? OrderDetailId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateDate { get; set; }

    [ForeignKey("ConcertId")]
    [InverseProperty("Seats")]
    public virtual Concert Concert { get; set; }
}