// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace TicketWave.Repository.Entity;

[Table("Seat")]
public partial class Seat
{
    [Key]
    public Guid SeatId { get; set; }

    public Guid? ConcertId { get; set; }
    public Guid? SportId { get; set; }
    public Guid? TheaterId { get; set; }

    [Required]
    [StringLength(20)]
    public string SeatZone { get; set; }

    [Required]
    [StringLength(10)]
    public string SeatRow { get; set; }

    [Required]
    [StringLength(10)]
    public string SeatNumber { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal Price { get; set; }

    public int SeatStatus { get; set; }

    public Guid? OrderDetailId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateDate { get; set; }

    [ForeignKey("ConcertId")]
    [InverseProperty("Seats")]
    public virtual Concert Concert { get; set; }

    [ForeignKey("SportId")]
    [InverseProperty("Seats")]
    public virtual Sport Sport { get; set; }

    [ForeignKey("TheaterId")]
    [InverseProperty("Seats")]
    public virtual Theater Theater { get; set; }
}