// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TicketWave.Repository.Entity;

public partial class TicketWaveContext : DbContext
{
    public TicketWaveContext(DbContextOptions<TicketWaveContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Concert> Concerts { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Seat> Seats { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_90_CI_AS");

        modelBuilder.Entity<Concert>(entity =>
        {
            entity.HasKey(e => e.ConcertId).HasName("PK_Concerts");

            entity.Property(e => e.ConcertId).ValueGeneratedNever();
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK_Members");

            entity.Property(e => e.MemberId)
                .ValueGeneratedNever()
                .HasComment("會員Id");
            entity.Property(e => e.Address).HasComment("地址");
            entity.Property(e => e.BirthDate).HasComment("生日");
            entity.Property(e => e.CreateDate).HasComment("建立日期");
            entity.Property(e => e.Email).HasComment("EMAIL");
            entity.Property(e => e.IsDelete).HasComment("是否刪除");
            entity.Property(e => e.Name).HasComment("會員姓名");
            entity.Property(e => e.NationalID).HasComment("身分證字號");
            entity.Property(e => e.Password)
                .HasDefaultValue("")
                .HasComment("密碼")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Members__Passwor__5AEE82B9");
            entity.Property(e => e.Phone).HasComment("手機");
            entity.Property(e => e.UpdateDate).HasComment("更新日期");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.Property(e => e.OrderId).ValueGeneratedNever();

            entity.HasOne(d => d.Member).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Order_Member");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.Property(e => e.OrderDetailId).ValueGeneratedNever();

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails).HasConstraintName("FK_OrderDetail_Order");
        });

        modelBuilder.Entity<Seat>(entity =>
        {
            entity.HasKey(e => e.SeatId).HasName("PK_Seats");

            entity.Property(e => e.SeatId).ValueGeneratedNever();

            entity.HasOne(d => d.Concert).WithMany(p => p.Seats)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Seat_Concert");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}